global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # TODO : exporter Asterisk (ex. asterisk-prometheus-exporter) une fois choisi
  # - job_name: "asterisk"
  #   static_configs:
  #     - targets: ["<HOST_IP>:9099"]