; VoxPME — extconfig.conf (contenu réel de la VM)
[settings]
ps_endpoint_id_ips => odbc,voxpme-db
ps_endpoints => odbc,voxpme-db
ps_auths => odbc,voxpme-db
ps_aors => odbc,voxpme-db
ps_transports => odbc,voxpme-db
queues => odbc,voxpme-db
queue_members => odbc,voxpme-db
ps_registrations => odbc,voxpme-db
extensions => odbc,voxpme-db
; test reload à chaud ajj 11 sep 2026 01:23:46 GMT
